"""
Python version used: 3.8.3
This program proceeses association rules file geneated by spmf java code into
a CSV format and stores it.
Inputs: a. Assoction rule file generated by spmf java code.

Output: CSV file containing association rule. 

How to run: python process_asso_rules.py <path to assoction rule file generated by spmf java code>
"""

import pandas as pd
import sys
def process_input(filename):

    with open(filename,"r+") as FH:
        lines = FH.readlines()
        df = pd.DataFrame(columns=["Antecedent","Consiquent","Support","Confidence"])

        for line in lines:
            x = line.split(' ==> ')
            antecedent = set(map(int,x[0].split(' ')))
            
            x = x[1].split(' #SUP: ')
            
            consequent = set(map(int,x[0].split(' ')))
            x = x[1].split(" #CONF: ")
        
            support = float(x[0])
            confidence = float(x[1].strip('\n'))
            #print("antecedent= {} consequent = {} support= {} confidence= {}".format(antecedent,consequent,support,confidence))
            #print("-"*30)
            df.loc[len(df)] = [antecedent,consequent,support,confidence]
            
        print(df.head(10))
        """
        Please provide the path where you would like to store the output of this program.
        """
        df.to_csv("output_files/kosarak/asso_rule_kosarak_03_01.csv",index=False)


if __name__ == '__main__':

    if len(sys.argv) != 2:
        raise SystemExit(f'Usage: {sys.argv[0]} ' 'Assoction rule file generated by spmf java code')

    filename = sys.argv[1]
    process_input(filename)